### ISSUE TITLE
Reference manual is still 8.9.0

### ISSUE THREAD

**Issue by Lysxia** [coq/www#118]
In https://coq.inria.fr/documentation, the "Reference Manual" links to:
- https://coq.inria.fr/distrib/current/refman/

which is still at 8.9.0.

There is more recent documentation here, is this its new home: https://coq.github.io/doc/ ?

**Comment by Lysxia** [comment]
Ah this seems to be issue #111 though if that issue takes long to solve it might be a good idea to think of a short-term solution specifically for the refman.

**Comment by Zimmi48** [comment]
@maximedenes Since the website migration, you are the only one who can solve this (I mean manually, even if I'd like to see the automatic solution proposed in #111 happen soon, hopefully for the 8.10 final release).

**Comment by maximedenes** [comment]
This is not just about a redirection, AFAICT nothing from 8.9.1 has been uploaded to the server (neither the old nor the new one). @silene is this a mistake? Where can I find the material to upload?

**Comment by Zimmi48** [comment]
@maximedenes https://coq.github.io/doc/V8.9.1/refman

**Comment by Zimmi48** [comment]
Let me just say this once more in a different way. Now that the manual is automatically deployed to GitHub pages, it would be stupid to expect a *separate*, *manual* deployment step at each release, when all we need to do is to point the reader to the right version of the manual *which is already on the web*.

**Comment by RalfJung** [comment]
Yeah, it is quite silly indeed that we have improved docs but still let users read old, outdated docs.

**Comment by maximedenes** [comment]
I'm still on holidays. I can do something as an emergency fix if you tell me precisely what you want me to do.

Alternatively, as I offered earlier, I can add your SSH key (@Zimmi48) to the VPS server so that you can tweak the configuration.

**Comment by Zimmi48** [comment]
This issue has waited for a while already, it's not like there is any emergency.

I'll send you my SSH key but I have no experience with Apache configuration, so it may take a while before I implement something, unless someone with experience tells me how to do.

Furthermore, I read on the internet that setting a transparent redirection requires activating `mod_proxy` which may not be something that SSH access is enough to do.

**Comment by maximedenes** [comment]
> @maximedenes https://coq.github.io/doc/V8.9.1/refman

Where can I find the pdf versions, though?

**Comment by maximedenes** [comment]
(I mean to redirect links to the pdf versions of refman and stdlib documentation)

**Comment by maximedenes** [comment]
Should be now fixed (using a reverse proxy), for the HTML versions.

**Comment by Zimmi48** [comment]
I have just uploaded the PDF version at https://github.com/coq/coq/releases/download/V8.9.1/coq-8.9.1-reference-manual.pdf, but I don't think that it deserves a redirection from anywhere, does it?

**Comment by maximedenes** [comment]
I mentioned it because we have this: https://coq.inria.fr/distrib/current/files/

**Comment by Zimmi48** [comment]
Yes, as I suggested in #111, let's kill it!

**Comment by Zimmi48** [comment]
Or let's redirect the whole thing to https://github.com/coq/coq/releases/latest
