### ISSUE TITLE
Mention, or link to the list of alternative UI directly on the front page.

### ISSUE THREAD

**Issue by Zimmi48** [coq/www#123]
Coq has now a growing set of well-maintained UI, and we should advertise this more prominently. The tool page is notoriously hard to update (two PRs have been opened for a while and never merged), completely outdated, and not the right name for a page listing UI anyways.

The list should be available on the front page, or a link should be added to the section "How to get Coq".

The UI to list are:
- Proof General for Emacs;
- Coqtail for Vim;
- VsCoq Reloaded (coq-community version) as soon as it is published on the VSCode marketplace which hopefully will be soon;
- JsCoq;
- The Coq Jupyter kernel.

See also coq/coq#10709.

**Comment by ejgallego** [comment]
Indeed this is long overdue; may I suggest that we also add some maturity/user-focus information. For example jsCoq is aimed at the introductory / first contact level, so it won't work well for large developments, etc...

**Comment by Zimmi48** [comment]
If we do a page for UI, we can definitely add this info, and even a small paragraph of presentation.

**Comment by Zimmi48** [comment]
WIP at #128.

**Comment by roptat** [comment]
Hi, I maintain a fork of coquille that I ported to neovim and newer coq versions here: https://framagit.org/tyreunom/coquille

Would you like to add it to your list?

**Comment by Zimmi48** [comment]
Sure, thanks for mentioning it. There were so many forks of coquille at some point, that I just lost track, and did not notice that yours was actively maintained. Sounds like the kind of things for which it would have been useful to have coq-community back in time.
