### ISSUE TITLE
Read the tutorial using Google Translate

### ISSUE THREAD

**Issue by ksoda** [coq/www#146]
Google Translate even targets the code. It changes the code and this significantly reduces the readability. I changed the class attribute to work around this. What do you think of these changes?
https://github.com/ksoda/www/commit/2ad23435b142db4d71d4c1863caedfb8e5393f35

**Comment by Zimmi48** [comment]
Hello, sorry for the delay in getting back to you. From the title, I didn't realize that you had some code to propose and I thought this was a feature request. Feel free to open a PR in such case to make the intent more obvious. I've merged your changes in master.

**Comment by Zimmi48** [comment]
Note though that officially this tutorial is "unmaintained" and might not work with recent versions of Coq.

**Comment by ksoda** [comment]
Sorry for the confusing title. And thank you for the merge.
Now I find that the [reference](https://coq.inria.fr/documentation) is at the top of the document with attention.
