### ISSUE TITLE
Installation instructions do not work on latest version of opam

### ISSUE THREAD

**Issue by JasonGross** [coq/www#175]
#### Description of the problem

https://coq.inria.fr/opam-using.html says
> Depending on your operating system, installing Coq using opam may require you to first install some system packages. The recommended way to determine the names of required system packages is via the opam-depext tool:
>
>     opam install opam-depext
>     opam-depext coq

However, the first command gives

```
[ERROR] opam-depext unmet availability conditions, e.g. 'opam-version >= "2.0.0~beta5" & opam-version < "2.1"'
```

**Comment by Zimmi48** [comment]
BTW, if you know what to change feel free to open a PR. The relevant file is: https://github.com/coq/www/blob/master/pages/opam-using.html

**Comment by JasonGross** [comment]
> Does `opam-depext` still work (without the previous step) or did the syntax change?

No, there is no `opam-depext` anymore, it happens automatically with `opam install`.

> It would be convenient if it could be fixed by just skipping the broken step in case opam >= 2.1 is detected.

Yes, we can just skip the opam depext steps in this case, as long as we can pass "y" to the relevant prompt.
