### ISSUE TITLE
coq.inria.fr/ is not working/reachable.

### ISSUE THREAD

**Issue by LumaKernel** [coq/www#209]
[coq.inria.fr/](https://coq.inria.fr/) looks not working now (name resolvable, but unreachable). I checked it was working a few days ago.

Used this site https://semonto.com/ to confirm it's unreachable from all the world.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/29811106/204579427-bf67febe-8778-448d-bf7d-a117f91a057c.png">

For users who wants to see docs for now, you can refer to github pages instead.
https://coq.github.io/doc/v8.17/refman/

**Comment by gares** [comment]
We are aware of this, see also https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Parts.20of.20website.20down.3F
