### ISSUE TITLE
This repository is looking for a maintainer

### ISSUE THREAD

**Issue by Zimmi48** [coq/www#45]
Who would be willing to watch this repository and provide feedback to people who open pull requests and merge them swiftly when they are ready?
Neither @maximedenes, nor I have time to do that but the lack of a maintainer makes contributing to the website a very difficult and frustrating task.

@ybertot: would you be willing to do this?
Or should it be @letouzey? (But I'm under the impression that Pierre is already overwhelmed by other tasks and has a lot to do with Coq anyway.)

**Comment by mattam82** [comment]
Oh right. I survey from time to time the PRs here and opam packages repo but didn't commit to doing it yet. I guess this is low volume so I can propose myself but I'd be happy to share responsibility

**Comment by ybertot** [comment]
I will share.

**Comment by Zimmi48** [comment]
I suppose that given the commitment of @mattam82 and @ybertot and given that most PRs have indeed been closed since then (with help of @letouzey), I suppose we can close this issue.
