### ISSUE TITLE
Missing right curly braces on the faq's bibtex entry

### ISSUE THREAD

**Issue by gallais** [coq/www#55]
It's a bit of a weird one: [the braces show up in the source](https://github.com/coq/www/blob/master/pages/faq.html#L3986) but [not on the website](https://coq.inria.fr/faq#htoc168)

**Comment by Zimmi48** [comment]
Note that the FAQ is in the process of being moved to the wiki (see https://github.com/coq/coq/issues/6180) and all corrections should now be done over there https://github.com/coq/coq/wiki/The-Coq-FAQ. As for this issue in particular, it is well rendered on the wiki, so I'm closing this.

(The https://coq.inria.fr/faq URL should soon be redirected to point to https://github.com/coq/coq/wiki/The-Coq-FAQ.)
