### ISSUE TITLE
Update version info on "Installing Coq via OPAM"

### ISSUE THREAD

**Issue by blefloch** [coq/www#58]
https://coq.inria.fr/opam/www/using.html gives the code

```bash
export OPAMROOT=~/opam-coq.8.6 # installation directory
opam init -n --comp=4.01.0 -j 2 # 2 is the number of CPU cores
opam repo add coq-released http://coq.inria.fr/opam/released
opam install coq.8.6 && opam pin add coq 8.6
```
It should be updated from 8.6 to 8.7.  I couldn't find any file named `using.html` in the present repo; please let me know if it is the wrong repo or the file is generated dynamically.

**Comment by blefloch** [comment]
I _think_ `4.01.0` should also be changed to `4.02.3` or higher, as it seems Coq 8.7 requires that, but I may be wrong.

**Comment by ejgallego** [comment]
You are absolutely correct; the canonical set of supported toolchains for Coq is stored in the `.travis.yml` file.

**Comment by Zimmi48** [comment]
Indeed, this is a bit misleading but this file is not in this repo but in https://github.com/coq/opam-coq-archive (cf `USING.md`). Feel free to open a PR over there fixing this. (As Emilio already said, you are fully correct on the OCaml requirements. They are documented in `INSTALL` as well.)
