### ISSUE TITLE
coq.inria.fr is down

### ISSUE THREAD

**Issue by paul-kline** [coq/www#64]
Help! Can't do any work as I need the reference manual.

**Comment by paul-kline** [comment]
Thanks for your promptness. Where would you recommend reading about the Coq Library for the time being? Specifically I would like to see https://coq.inria.fr/library/Coq.Logic.FunctionalExtensionality.html . Some older proofs of mine are broken written for an older version and I would like to see what has changed.

**Comment by maximedenes** [comment]
Maybe you can use `git log` on that file? Or using GitHub: https://github.com/coq/coq/commits/master/theories/Logic/FunctionalExtensionality.v

**Comment by paul-kline** [comment]
any suggestion  for viewing library documentation (tactics, etc)?

**Comment by Zimmi48** [comment]
The website is back on.

**Comment by maximedenes** [comment]
Yes, but it is back up because I randomly restarted the web server myself. We should make the whole infrastructure reliable.
