### ISSUE TITLE
What shall we do with the distrib directory?

### ISSUE THREAD

**Issue by vbgl** [coq/www#88]
On the Coq website, the https://coq.inria.fr/distrib/ directory holds about 16 Gio of History. Do we want to keep it online? If so, where and how? In particular, it does not fit well with a move to a lighter web infrastructure as envisioned in #82.

Notice that recent releases are already available at https://github.com/coq/coq/releases/.

NB: I know that the manual of the current version is also stored in that directory; it does not count as “History” and I’m taking care of integrating it to the reworked website. Thus this is not the matter of this PR. Thanks.

Suggestions welcome.

**Comment by Zimmi48** [comment]
I was going to suggest relying on https://web.archive.org/ to store the old parts of the website. However, it seems like a `robots.txt` file is actually *preventing* the Wayback Machine from doing that! (check out https://web.archive.org/save/http://coq.inria.fr/distrib/).

**Comment by Zimmi48** [comment]
@maximedenes It seems that the strategy that has been follow is to not rely exclusively on GH pages so this issue and #82 could be closed now, right?

**Comment by maximedenes** [comment]
> It seems that the strategy that has been follow is to not rely exclusively on GH pages so this issue and #82 could be closed now, right?

The strategy is to make small steps. It is still not clear to me if we can target GitHub pages in the long run or not.

**Comment by Zimmi48** [comment]
I suggest closing these issues because we are not planning any specific action right now. The information that is in there is not lost when the issues are closed.
