### ISSUE TITLE
Why does the "Using OPAM to install Coq" instructions set OPAMROOT instead of using switches?

### ISSUE THREAD

**Issue by Lysxia** [coq/www#95]
Switches strike me as the more principled way of managing distinct opam environments.

**Comment by Zimmi48** [comment]
It is most likely dating back from a time when it was difficult to set up different switches with the same OCaml compiler. A PR improving these instructions would be welcome I think (see also coq/opam-coq-archive#595).

**Comment by Zimmi48** [comment]
It seems like the conclusion of #96 was that there are good reasons for things as they are.

**Comment by ejgallego** [comment]
The fact that we recommend the minimum supported compiler is still not satisfactory tho. There are downsides to using and older OCaml version.

Even if the opam repository doesn't test a newer compiler, the CI system does test against the newer versions, (I forgot what switch does pkg:opam select tho)
